version: "3.9"  # optional since v1.27.0
services:
  angularprojectcreate:
          # build: .
    image: angu
    volumes:
      - ./${PROJECT}:/project/${PROJECT}
      - ./npmscript:/data/pm2script
    environment:
      - PROJECT=${PROJECT}
    command: >
      bash -c "ng new ${PROJECT} && cd ${PROJECT} && ng add @nguniversal/express-engine --skip-confirmation "
